config/routes.rb
Rails.application.routes.draw do

	root "posts#index"

	get '/posts', to: 'posts#index', as: 'posts'
	get '/users/:user_id/posts', to: 'posts#user_posts_index', as: 'user_posts'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

	resources :users, except: :index do 
	  resources :posts, except: :index
	end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

	has_many :posts

  validates :password_digest, :email, { presence: true }
  validates_uniqueness_of :email

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # 	protect_from_forgery with: :exception

  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
  # helper_method :current_user

  # def authorize
  #   redirect_to '/login' unless current_user
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

  def user_posts_index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

	def show
		@post = Post.find(params[:id])
	end

	def new
    user = User.find(params[:user_id])
		@post = user.posts.new
	end 

	def create
    user = User.find(params[:user_id])
    @post = user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, :notice => "New post was saved"
    else
      render "new"
    end 
	end

	def edit
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end 

	def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
    	redirect_to user_post_path(@post.id), :notice => "Your post has been updated"
    else
      render "edit"
    end 
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end


  private

    def post_params
      params.require(:post).permit(:title, :body, :user_id, tags: [])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

include SessionHelper

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session_logout
    redirect_to root_path
  end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end 

	def create
    @user = User.new(user_params)

    if @user.save
      session_login
      redirect_to users_path, :notice => "New User was saved"
    else 
      render "new"
    end 
	end

	def edit
    @user = User.find(params[:id])
  end 

	def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    	redirect_to user_path(@user.id), :notice => "User has been updated"
    else
      render "edit"
    end 
  end

  def destroy

    user = User.find(params[:id])
    Post.delete_all(user_id: user.id)
    user.destroy
    redirect_to root_path
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def session_logged_in?
    !session[:user_id].nil?
  end

  def session_current_user
    begin
      @current_user ||= User.find(session[:user_id])
    rescue ActiveRecord::RecordNotFound => e
      session.clear
      @current_user = nil
    end
  end

  def session_logout
    session.clear
  end

  def session_login user
    session[:user_id] = user.id
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <ul class="nav navbar-nav navbar-left">
    	<li id=title><%= link_to "HAMBLOG", posts_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to "Posts", posts_path %></li>
      <% if session_logged_in? %>
      <li> <%= link_to "Profile", user_path(session_current_user) %> </li>
      <li> <%= link_to "Log out", logout_path, method: :delete %> </li>
      <% else %>
      <li> <%= link_to "Login", login_path %> </li>
      <li> <%= link_to "Sign up", new_user_path %> </li>
      <% end %>
    </ul>
  </div>  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HAMBLOG</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
      <div class="jumbotron">
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h4>Update Post </h4>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@post.user, @post] do |f| %>
      <%= f.label "Title" %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label "Body" %>
      <%= f.text_field :body, class: 'form-control' %>
      <%= f.submit "Save changes", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h2><%= link_to post.title, user_post_path(post.user, post) %></h2>
  <p><%= post.body %></p>
	<h4>user: <%= post.user.name %></h4><br>

	<% if post.tags.length > 0 %>
		<h4>tags:</h4>
		<% post.tags.each do |tag| %>
			<h5><%= tag %></h5>
		<% end %>
	<% end %>
<% end %>

app/views/posts/new.html.erb
<h4>New Post </h4>
<div class="row">
  <div class="col-md-6">
    <%= form_for [@post.user, @post] do |f| %>
      <%= f.label "title" %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label "body" %>
      <%= f.text_field :body, class: 'form-control' %>
      <%= f.label "tags" %>
      <div class="form-inline form-group-sm classes">
        <%= f.text_field :tags, multiple: true, class: 'form-control' %>
        <%= f.text_field :tags, multiple: true, class: 'form-control' %>
        <%= f.text_field :tags, multiple: true, class: 'form-control' %>
      </div>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
  <h2><%= @post.title %></h2>
  <p><%= @post.body %></p>
  <td><%= link_to "Edit", edit_user_post_path(@post.user, @post) %></td>
  <td><%= link_to "Delete", [@post.user, @post], method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %></td>

app/views/posts/user_posts_index.html.erb
<h3><%= @user.name %> Posts <h3>

<% @posts.each do |post| %>
  <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
  <p><%= post.body %></p>
  <td><%= link_to "Edit", edit_user_post_path(@user, post) %></td>
  <td><%= link_to "Delete", [@user, post], method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %></td>
<% end %>

app/views/users/edit.html.erb
<h4>Update User </h4>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= f.label "Name" %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.submit "Save changes", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h4>New User </h4>
<div class="row">
  <div class="col-md-6">
    <%= form_for @user do |f| %>

      <%= f.label "Name" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h4><%= @user.name %></h4>
<h5><%= link_to "Edit Profile", edit_user_path(@user) %></h5> 
<h5><%= link_to "Delete Profile", @user, method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %></h5> 
<h5><%= link_to "Posts", user_posts_path(@user) %></h5>
<h5><%= link_to "Create Post", new_user_post_path(@user) %></h5> 